// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preset.proto

package protos;

public interface CreatePresetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreatePresetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.PresetObj preset = 1;</code>
   * @return Whether the preset field is set.
   */
  boolean hasPreset();
  /**
   * <code>.PresetObj preset = 1;</code>
   * @return The preset.
   */
  protos.PresetObj getPreset();
  /**
   * <code>.PresetObj preset = 1;</code>
   */
  protos.PresetObjOrBuilder getPresetOrBuilder();
}
