// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preset.proto

package protos;

public interface GetPresetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetPresetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string Id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
