// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preset.proto

package protos;

public interface ListPresetsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListPresetsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 Limit = 1;</code>
   * @return The limit.
   */
  int getLimit();
}
