// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preset.proto

package protos;

/**
 * Protobuf type {@code ListPresetsResponse}
 */
public final class ListPresetsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ListPresetsResponse)
    ListPresetsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListPresetsResponse.newBuilder() to construct.
  private ListPresetsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListPresetsResponse() {
    presets_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListPresetsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListPresetsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              presets_ = new java.util.ArrayList<protos.PresetObj>();
              mutable_bitField0_ |= 0x00000001;
            }
            presets_.add(
                input.readMessage(protos.PresetObj.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        presets_ = java.util.Collections.unmodifiableList(presets_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protos.Preset.internal_static_ListPresetsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protos.Preset.internal_static_ListPresetsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protos.ListPresetsResponse.class, protos.ListPresetsResponse.Builder.class);
  }

  public static final int PRESETS_FIELD_NUMBER = 1;
  private java.util.List<protos.PresetObj> presets_;
  /**
   * <code>repeated .PresetObj presets = 1;</code>
   */
  @java.lang.Override
  public java.util.List<protos.PresetObj> getPresetsList() {
    return presets_;
  }
  /**
   * <code>repeated .PresetObj presets = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protos.PresetObjOrBuilder> 
      getPresetsOrBuilderList() {
    return presets_;
  }
  /**
   * <code>repeated .PresetObj presets = 1;</code>
   */
  @java.lang.Override
  public int getPresetsCount() {
    return presets_.size();
  }
  /**
   * <code>repeated .PresetObj presets = 1;</code>
   */
  @java.lang.Override
  public protos.PresetObj getPresets(int index) {
    return presets_.get(index);
  }
  /**
   * <code>repeated .PresetObj presets = 1;</code>
   */
  @java.lang.Override
  public protos.PresetObjOrBuilder getPresetsOrBuilder(
      int index) {
    return presets_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < presets_.size(); i++) {
      output.writeMessage(1, presets_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < presets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, presets_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protos.ListPresetsResponse)) {
      return super.equals(obj);
    }
    protos.ListPresetsResponse other = (protos.ListPresetsResponse) obj;

    if (!getPresetsList()
        .equals(other.getPresetsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPresetsCount() > 0) {
      hash = (37 * hash) + PRESETS_FIELD_NUMBER;
      hash = (53 * hash) + getPresetsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protos.ListPresetsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protos.ListPresetsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protos.ListPresetsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protos.ListPresetsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protos.ListPresetsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protos.ListPresetsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protos.ListPresetsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protos.ListPresetsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protos.ListPresetsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protos.ListPresetsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protos.ListPresetsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protos.ListPresetsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protos.ListPresetsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ListPresetsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ListPresetsResponse)
      protos.ListPresetsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.Preset.internal_static_ListPresetsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.Preset.internal_static_ListPresetsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.ListPresetsResponse.class, protos.ListPresetsResponse.Builder.class);
    }

    // Construct using protos.ListPresetsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPresetsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (presetsBuilder_ == null) {
        presets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        presetsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protos.Preset.internal_static_ListPresetsResponse_descriptor;
    }

    @java.lang.Override
    public protos.ListPresetsResponse getDefaultInstanceForType() {
      return protos.ListPresetsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public protos.ListPresetsResponse build() {
      protos.ListPresetsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protos.ListPresetsResponse buildPartial() {
      protos.ListPresetsResponse result = new protos.ListPresetsResponse(this);
      int from_bitField0_ = bitField0_;
      if (presetsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          presets_ = java.util.Collections.unmodifiableList(presets_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.presets_ = presets_;
      } else {
        result.presets_ = presetsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protos.ListPresetsResponse) {
        return mergeFrom((protos.ListPresetsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protos.ListPresetsResponse other) {
      if (other == protos.ListPresetsResponse.getDefaultInstance()) return this;
      if (presetsBuilder_ == null) {
        if (!other.presets_.isEmpty()) {
          if (presets_.isEmpty()) {
            presets_ = other.presets_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePresetsIsMutable();
            presets_.addAll(other.presets_);
          }
          onChanged();
        }
      } else {
        if (!other.presets_.isEmpty()) {
          if (presetsBuilder_.isEmpty()) {
            presetsBuilder_.dispose();
            presetsBuilder_ = null;
            presets_ = other.presets_;
            bitField0_ = (bitField0_ & ~0x00000001);
            presetsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPresetsFieldBuilder() : null;
          } else {
            presetsBuilder_.addAllMessages(other.presets_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protos.ListPresetsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protos.ListPresetsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<protos.PresetObj> presets_ =
      java.util.Collections.emptyList();
    private void ensurePresetsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        presets_ = new java.util.ArrayList<protos.PresetObj>(presets_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protos.PresetObj, protos.PresetObj.Builder, protos.PresetObjOrBuilder> presetsBuilder_;

    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public java.util.List<protos.PresetObj> getPresetsList() {
      if (presetsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(presets_);
      } else {
        return presetsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public int getPresetsCount() {
      if (presetsBuilder_ == null) {
        return presets_.size();
      } else {
        return presetsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public protos.PresetObj getPresets(int index) {
      if (presetsBuilder_ == null) {
        return presets_.get(index);
      } else {
        return presetsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public Builder setPresets(
        int index, protos.PresetObj value) {
      if (presetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePresetsIsMutable();
        presets_.set(index, value);
        onChanged();
      } else {
        presetsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public Builder setPresets(
        int index, protos.PresetObj.Builder builderForValue) {
      if (presetsBuilder_ == null) {
        ensurePresetsIsMutable();
        presets_.set(index, builderForValue.build());
        onChanged();
      } else {
        presetsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public Builder addPresets(protos.PresetObj value) {
      if (presetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePresetsIsMutable();
        presets_.add(value);
        onChanged();
      } else {
        presetsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public Builder addPresets(
        int index, protos.PresetObj value) {
      if (presetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePresetsIsMutable();
        presets_.add(index, value);
        onChanged();
      } else {
        presetsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public Builder addPresets(
        protos.PresetObj.Builder builderForValue) {
      if (presetsBuilder_ == null) {
        ensurePresetsIsMutable();
        presets_.add(builderForValue.build());
        onChanged();
      } else {
        presetsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public Builder addPresets(
        int index, protos.PresetObj.Builder builderForValue) {
      if (presetsBuilder_ == null) {
        ensurePresetsIsMutable();
        presets_.add(index, builderForValue.build());
        onChanged();
      } else {
        presetsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public Builder addAllPresets(
        java.lang.Iterable<? extends protos.PresetObj> values) {
      if (presetsBuilder_ == null) {
        ensurePresetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, presets_);
        onChanged();
      } else {
        presetsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public Builder clearPresets() {
      if (presetsBuilder_ == null) {
        presets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        presetsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public Builder removePresets(int index) {
      if (presetsBuilder_ == null) {
        ensurePresetsIsMutable();
        presets_.remove(index);
        onChanged();
      } else {
        presetsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public protos.PresetObj.Builder getPresetsBuilder(
        int index) {
      return getPresetsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public protos.PresetObjOrBuilder getPresetsOrBuilder(
        int index) {
      if (presetsBuilder_ == null) {
        return presets_.get(index);  } else {
        return presetsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public java.util.List<? extends protos.PresetObjOrBuilder> 
         getPresetsOrBuilderList() {
      if (presetsBuilder_ != null) {
        return presetsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(presets_);
      }
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public protos.PresetObj.Builder addPresetsBuilder() {
      return getPresetsFieldBuilder().addBuilder(
          protos.PresetObj.getDefaultInstance());
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public protos.PresetObj.Builder addPresetsBuilder(
        int index) {
      return getPresetsFieldBuilder().addBuilder(
          index, protos.PresetObj.getDefaultInstance());
    }
    /**
     * <code>repeated .PresetObj presets = 1;</code>
     */
    public java.util.List<protos.PresetObj.Builder> 
         getPresetsBuilderList() {
      return getPresetsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protos.PresetObj, protos.PresetObj.Builder, protos.PresetObjOrBuilder> 
        getPresetsFieldBuilder() {
      if (presetsBuilder_ == null) {
        presetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protos.PresetObj, protos.PresetObj.Builder, protos.PresetObjOrBuilder>(
                presets_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        presets_ = null;
      }
      return presetsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ListPresetsResponse)
  }

  // @@protoc_insertion_point(class_scope:ListPresetsResponse)
  private static final protos.ListPresetsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protos.ListPresetsResponse();
  }

  public static protos.ListPresetsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListPresetsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListPresetsResponse>() {
    @java.lang.Override
    public ListPresetsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListPresetsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListPresetsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListPresetsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protos.ListPresetsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

