// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preset.proto

package protos;

public final class Preset {
  private Preset() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PresetObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PresetObj_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreatePresetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreatePresetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreatePresetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreatePresetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeletePresetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeletePresetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeletePresetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeletePresetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPresetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPresetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPresetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPresetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListPresetsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListPresetsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListPresetsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListPresetsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdatePresetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdatePresetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdatePresetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdatePresetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014preset.proto\"\261\001\n\tPresetObj\022\n\n\002Id\030\001 \001(\005" +
      "\022\014\n\004Name\030\002 \001(\t\022\023\n\013MinHumidity\030\003 \001(\002\022\023\n\013M" +
      "axHumidity\030\004 \001(\002\022\016\n\006MinCo2\030\005 \001(\002\022\016\n\006MaxC" +
      "o2\030\006 \001(\002\022\026\n\016MinTemperature\030\007 \001(\002\022\026\n\016MaxT" +
      "emperature\030\010 \001(\002\022\020\n\010deviceId\030\t \001(\t\"1\n\023Cr" +
      "eatePresetRequest\022\032\n\006preset\030\001 \001(\0132\n.Pres" +
      "etObj\"2\n\024CreatePresetResponse\022\032\n\006preset\030" +
      "\001 \001(\0132\n.PresetObj\"!\n\023DeletePresetRequest" +
      "\022\n\n\002Id\030\001 \001(\t\"\"\n\024DeletePresetResponse\022\n\n\002" +
      "Id\030\001 \001(\t\"\036\n\020GetPresetRequest\022\n\n\002Id\030\001 \001(\t" +
      "\"/\n\021GetPresetResponse\022\032\n\006preset\030\001 \001(\0132\n." +
      "PresetObj\"#\n\022ListPresetsRequest\022\r\n\005Limit" +
      "\030\001 \001(\005\"2\n\023ListPresetsResponse\022\033\n\007presets" +
      "\030\001 \003(\0132\n.PresetObj\"1\n\023UpdatePresetReques" +
      "t\022\032\n\006preset\030\001 \001(\0132\n.PresetObj\"2\n\024UpdateP" +
      "resetResponse\022\032\n\006preset\030\001 \001(\0132\n.PresetOb" +
      "j2\303\002\n\022PresetServiceProto\022=\n\014CreatePreset" +
      "\022\024.CreatePresetRequest\032\025.CreatePresetRes" +
      "ponse\"\000\022=\n\014DeletePreset\022\024.DeletePresetRe" +
      "quest\032\025.DeletePresetResponse\"\000\0224\n\tGetPre" +
      "set\022\021.GetPresetRequest\032\022.GetPresetRespon" +
      "se\"\000\022:\n\013ListPresets\022\023.ListPresetsRequest" +
      "\032\024.ListPresetsResponse\"\000\022=\n\014UpdatePreset" +
      "\022\024.UpdatePresetRequest\032\025.UpdatePresetRes" +
      "ponse\"\000B\n\n\006protosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PresetObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PresetObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PresetObj_descriptor,
        new java.lang.String[] { "Id", "Name", "MinHumidity", "MaxHumidity", "MinCo2", "MaxCo2", "MinTemperature", "MaxTemperature", "DeviceId", });
    internal_static_CreatePresetRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CreatePresetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreatePresetRequest_descriptor,
        new java.lang.String[] { "Preset", });
    internal_static_CreatePresetResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CreatePresetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreatePresetResponse_descriptor,
        new java.lang.String[] { "Preset", });
    internal_static_DeletePresetRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DeletePresetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeletePresetRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeletePresetResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_DeletePresetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeletePresetResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetPresetRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetPresetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPresetRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetPresetResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetPresetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPresetResponse_descriptor,
        new java.lang.String[] { "Preset", });
    internal_static_ListPresetsRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ListPresetsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListPresetsRequest_descriptor,
        new java.lang.String[] { "Limit", });
    internal_static_ListPresetsResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ListPresetsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListPresetsResponse_descriptor,
        new java.lang.String[] { "Presets", });
    internal_static_UpdatePresetRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_UpdatePresetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdatePresetRequest_descriptor,
        new java.lang.String[] { "Preset", });
    internal_static_UpdatePresetResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_UpdatePresetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdatePresetResponse_descriptor,
        new java.lang.String[] { "Preset", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
