// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preset.proto

package protos;

/**
 * Protobuf type {@code PresetObj}
 */
public final class PresetObj extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PresetObj)
    PresetObjOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PresetObj.newBuilder() to construct.
  private PresetObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PresetObj() {
    name_ = "";
    deviceId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PresetObj();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PresetObj(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 29: {

            minHumidity_ = input.readFloat();
            break;
          }
          case 37: {

            maxHumidity_ = input.readFloat();
            break;
          }
          case 45: {

            minCo2_ = input.readFloat();
            break;
          }
          case 53: {

            maxCo2_ = input.readFloat();
            break;
          }
          case 61: {

            minTemperature_ = input.readFloat();
            break;
          }
          case 69: {

            maxTemperature_ = input.readFloat();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protos.Preset.internal_static_PresetObj_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protos.Preset.internal_static_PresetObj_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protos.PresetObj.class, protos.PresetObj.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 Id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string Name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string Name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MINHUMIDITY_FIELD_NUMBER = 3;
  private float minHumidity_;
  /**
   * <code>float MinHumidity = 3;</code>
   * @return The minHumidity.
   */
  @java.lang.Override
  public float getMinHumidity() {
    return minHumidity_;
  }

  public static final int MAXHUMIDITY_FIELD_NUMBER = 4;
  private float maxHumidity_;
  /**
   * <code>float MaxHumidity = 4;</code>
   * @return The maxHumidity.
   */
  @java.lang.Override
  public float getMaxHumidity() {
    return maxHumidity_;
  }

  public static final int MINCO2_FIELD_NUMBER = 5;
  private float minCo2_;
  /**
   * <code>float MinCo2 = 5;</code>
   * @return The minCo2.
   */
  @java.lang.Override
  public float getMinCo2() {
    return minCo2_;
  }

  public static final int MAXCO2_FIELD_NUMBER = 6;
  private float maxCo2_;
  /**
   * <code>float MaxCo2 = 6;</code>
   * @return The maxCo2.
   */
  @java.lang.Override
  public float getMaxCo2() {
    return maxCo2_;
  }

  public static final int MINTEMPERATURE_FIELD_NUMBER = 7;
  private float minTemperature_;
  /**
   * <code>float MinTemperature = 7;</code>
   * @return The minTemperature.
   */
  @java.lang.Override
  public float getMinTemperature() {
    return minTemperature_;
  }

  public static final int MAXTEMPERATURE_FIELD_NUMBER = 8;
  private float maxTemperature_;
  /**
   * <code>float MaxTemperature = 8;</code>
   * @return The maxTemperature.
   */
  @java.lang.Override
  public float getMaxTemperature() {
    return maxTemperature_;
  }

  public static final int DEVICEID_FIELD_NUMBER = 9;
  private volatile java.lang.Object deviceId_;
  /**
   * <code>string deviceId = 9;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <code>string deviceId = 9;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (java.lang.Float.floatToRawIntBits(minHumidity_) != 0) {
      output.writeFloat(3, minHumidity_);
    }
    if (java.lang.Float.floatToRawIntBits(maxHumidity_) != 0) {
      output.writeFloat(4, maxHumidity_);
    }
    if (java.lang.Float.floatToRawIntBits(minCo2_) != 0) {
      output.writeFloat(5, minCo2_);
    }
    if (java.lang.Float.floatToRawIntBits(maxCo2_) != 0) {
      output.writeFloat(6, maxCo2_);
    }
    if (java.lang.Float.floatToRawIntBits(minTemperature_) != 0) {
      output.writeFloat(7, minTemperature_);
    }
    if (java.lang.Float.floatToRawIntBits(maxTemperature_) != 0) {
      output.writeFloat(8, maxTemperature_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, deviceId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (java.lang.Float.floatToRawIntBits(minHumidity_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, minHumidity_);
    }
    if (java.lang.Float.floatToRawIntBits(maxHumidity_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, maxHumidity_);
    }
    if (java.lang.Float.floatToRawIntBits(minCo2_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, minCo2_);
    }
    if (java.lang.Float.floatToRawIntBits(maxCo2_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, maxCo2_);
    }
    if (java.lang.Float.floatToRawIntBits(minTemperature_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(7, minTemperature_);
    }
    if (java.lang.Float.floatToRawIntBits(maxTemperature_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(8, maxTemperature_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, deviceId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protos.PresetObj)) {
      return super.equals(obj);
    }
    protos.PresetObj other = (protos.PresetObj) obj;

    if (getId()
        != other.getId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (java.lang.Float.floatToIntBits(getMinHumidity())
        != java.lang.Float.floatToIntBits(
            other.getMinHumidity())) return false;
    if (java.lang.Float.floatToIntBits(getMaxHumidity())
        != java.lang.Float.floatToIntBits(
            other.getMaxHumidity())) return false;
    if (java.lang.Float.floatToIntBits(getMinCo2())
        != java.lang.Float.floatToIntBits(
            other.getMinCo2())) return false;
    if (java.lang.Float.floatToIntBits(getMaxCo2())
        != java.lang.Float.floatToIntBits(
            other.getMaxCo2())) return false;
    if (java.lang.Float.floatToIntBits(getMinTemperature())
        != java.lang.Float.floatToIntBits(
            other.getMinTemperature())) return false;
    if (java.lang.Float.floatToIntBits(getMaxTemperature())
        != java.lang.Float.floatToIntBits(
            other.getMaxTemperature())) return false;
    if (!getDeviceId()
        .equals(other.getDeviceId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + MINHUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMinHumidity());
    hash = (37 * hash) + MAXHUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMaxHumidity());
    hash = (37 * hash) + MINCO2_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMinCo2());
    hash = (37 * hash) + MAXCO2_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMaxCo2());
    hash = (37 * hash) + MINTEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMinTemperature());
    hash = (37 * hash) + MAXTEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMaxTemperature());
    hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protos.PresetObj parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protos.PresetObj parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protos.PresetObj parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protos.PresetObj parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protos.PresetObj parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protos.PresetObj parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protos.PresetObj parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protos.PresetObj parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protos.PresetObj parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protos.PresetObj parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protos.PresetObj parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protos.PresetObj parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protos.PresetObj prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PresetObj}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PresetObj)
      protos.PresetObjOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.Preset.internal_static_PresetObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.Preset.internal_static_PresetObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.PresetObj.class, protos.PresetObj.Builder.class);
    }

    // Construct using protos.PresetObj.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      name_ = "";

      minHumidity_ = 0F;

      maxHumidity_ = 0F;

      minCo2_ = 0F;

      maxCo2_ = 0F;

      minTemperature_ = 0F;

      maxTemperature_ = 0F;

      deviceId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protos.Preset.internal_static_PresetObj_descriptor;
    }

    @java.lang.Override
    public protos.PresetObj getDefaultInstanceForType() {
      return protos.PresetObj.getDefaultInstance();
    }

    @java.lang.Override
    public protos.PresetObj build() {
      protos.PresetObj result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protos.PresetObj buildPartial() {
      protos.PresetObj result = new protos.PresetObj(this);
      result.id_ = id_;
      result.name_ = name_;
      result.minHumidity_ = minHumidity_;
      result.maxHumidity_ = maxHumidity_;
      result.minCo2_ = minCo2_;
      result.maxCo2_ = maxCo2_;
      result.minTemperature_ = minTemperature_;
      result.maxTemperature_ = maxTemperature_;
      result.deviceId_ = deviceId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protos.PresetObj) {
        return mergeFrom((protos.PresetObj)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protos.PresetObj other) {
      if (other == protos.PresetObj.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getMinHumidity() != 0F) {
        setMinHumidity(other.getMinHumidity());
      }
      if (other.getMaxHumidity() != 0F) {
        setMaxHumidity(other.getMaxHumidity());
      }
      if (other.getMinCo2() != 0F) {
        setMinCo2(other.getMinCo2());
      }
      if (other.getMaxCo2() != 0F) {
        setMaxCo2(other.getMaxCo2());
      }
      if (other.getMinTemperature() != 0F) {
        setMinTemperature(other.getMinTemperature());
      }
      if (other.getMaxTemperature() != 0F) {
        setMaxTemperature(other.getMaxTemperature());
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protos.PresetObj parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protos.PresetObj) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 Id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 Id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string Name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string Name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private float minHumidity_ ;
    /**
     * <code>float MinHumidity = 3;</code>
     * @return The minHumidity.
     */
    @java.lang.Override
    public float getMinHumidity() {
      return minHumidity_;
    }
    /**
     * <code>float MinHumidity = 3;</code>
     * @param value The minHumidity to set.
     * @return This builder for chaining.
     */
    public Builder setMinHumidity(float value) {
      
      minHumidity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float MinHumidity = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinHumidity() {
      
      minHumidity_ = 0F;
      onChanged();
      return this;
    }

    private float maxHumidity_ ;
    /**
     * <code>float MaxHumidity = 4;</code>
     * @return The maxHumidity.
     */
    @java.lang.Override
    public float getMaxHumidity() {
      return maxHumidity_;
    }
    /**
     * <code>float MaxHumidity = 4;</code>
     * @param value The maxHumidity to set.
     * @return This builder for chaining.
     */
    public Builder setMaxHumidity(float value) {
      
      maxHumidity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float MaxHumidity = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxHumidity() {
      
      maxHumidity_ = 0F;
      onChanged();
      return this;
    }

    private float minCo2_ ;
    /**
     * <code>float MinCo2 = 5;</code>
     * @return The minCo2.
     */
    @java.lang.Override
    public float getMinCo2() {
      return minCo2_;
    }
    /**
     * <code>float MinCo2 = 5;</code>
     * @param value The minCo2 to set.
     * @return This builder for chaining.
     */
    public Builder setMinCo2(float value) {
      
      minCo2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float MinCo2 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinCo2() {
      
      minCo2_ = 0F;
      onChanged();
      return this;
    }

    private float maxCo2_ ;
    /**
     * <code>float MaxCo2 = 6;</code>
     * @return The maxCo2.
     */
    @java.lang.Override
    public float getMaxCo2() {
      return maxCo2_;
    }
    /**
     * <code>float MaxCo2 = 6;</code>
     * @param value The maxCo2 to set.
     * @return This builder for chaining.
     */
    public Builder setMaxCo2(float value) {
      
      maxCo2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float MaxCo2 = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxCo2() {
      
      maxCo2_ = 0F;
      onChanged();
      return this;
    }

    private float minTemperature_ ;
    /**
     * <code>float MinTemperature = 7;</code>
     * @return The minTemperature.
     */
    @java.lang.Override
    public float getMinTemperature() {
      return minTemperature_;
    }
    /**
     * <code>float MinTemperature = 7;</code>
     * @param value The minTemperature to set.
     * @return This builder for chaining.
     */
    public Builder setMinTemperature(float value) {
      
      minTemperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float MinTemperature = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinTemperature() {
      
      minTemperature_ = 0F;
      onChanged();
      return this;
    }

    private float maxTemperature_ ;
    /**
     * <code>float MaxTemperature = 8;</code>
     * @return The maxTemperature.
     */
    @java.lang.Override
    public float getMaxTemperature() {
      return maxTemperature_;
    }
    /**
     * <code>float MaxTemperature = 8;</code>
     * @param value The maxTemperature to set.
     * @return This builder for chaining.
     */
    public Builder setMaxTemperature(float value) {
      
      maxTemperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float MaxTemperature = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxTemperature() {
      
      maxTemperature_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object deviceId_ = "";
    /**
     * <code>string deviceId = 9;</code>
     * @return The deviceId.
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string deviceId = 9;</code>
     * @return The bytes for deviceId.
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string deviceId = 9;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string deviceId = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
      onChanged();
      return this;
    }
    /**
     * <code>string deviceId = 9;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PresetObj)
  }

  // @@protoc_insertion_point(class_scope:PresetObj)
  private static final protos.PresetObj DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protos.PresetObj();
  }

  public static protos.PresetObj getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PresetObj>
      PARSER = new com.google.protobuf.AbstractParser<PresetObj>() {
    @java.lang.Override
    public PresetObj parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PresetObj(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PresetObj> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PresetObj> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protos.PresetObj getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

