// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package protos;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UserObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UserObj_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Username_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Username_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\005proto\"H\n\007UserObj\022\n\n\002id\030\001 \001" +
      "(\005\022\020\n\010username\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\r" +
      "\n\005email\030\004 \001(\t\"\034\n\010Username\022\020\n\010username\030\001 " +
      "\001(\t2d\n\013UserService\022)\n\007AddUser\022\016.proto.Us" +
      "erObj\032\016.proto.UserObj\022*\n\007GetUser\022\017.proto" +
      ".Username\032\016.proto.UserObjB\n\n\006protosP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_UserObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_UserObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UserObj_descriptor,
        new java.lang.String[] { "Id", "Username", "Password", "Email", });
    internal_static_proto_Username_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Username_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Username_descriptor,
        new java.lang.String[] { "Username", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
