name: Build and Deploy to Google Cloud Platform

on:
  push:
    branches: [main]

jobs:
  build-push-gcr:
    name: Build and push to GCR
    runs-on: ubuntu-latest
    env:
      IMAGE_BACKEND: backend-server
      PROJECT_ID: sep4-386214
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Build Docker Images
      run: docker compose build

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    - name: Push Docker to Container Registry (GCR)
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_BACKEND:latest gcr.io/$PROJECT_ID/$IMAGE_BACKEND:latest
        docker tag $IMAGE_BACKEND:latest gcr.io/$PROJECT_ID/$IMAGE_BACKEND:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_BACKEND:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_BACKEND:$GIT_TAG