name: GitHub Actions Demo
run-name: ${{ github.actor }} is just playing around 8)
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
